name: prebuild-check
on:
  push:
    branches:
      - main
    paths:
      - 'libs/ui/**'
      - '.github/workflows/**'
  pull_request:
      branches:
      types: [opened, synchronize, reopened]
jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          always-auth: true

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint:all

      - name: Run unit tests coverage
        run: yarn lib:cov

      - name: Change absolute path to relative path in coverage
        run: sed -i "s|SF:/.*/src/|SF:/github/workspace/src/|g" coverage/lcov.info
      #########################
        # Run SonarCloud Analysis
      #########################
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: libs/ui
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.testExecutionReportPaths=reports/test-report.xml